{% set name = "DoubleMetaphone" %}
{% set version = "1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  # Use upstream archive tarball for tests
  url: https://github.com/dedupeio/doublemetaphone/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 69eb748a08e8d7d7f4448e8bfbc9b5d5018d979067c9b48c62d121633e4f7b55

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - setuptools
    - wheel
    - cython
  run:
    - python

test:
  source_files:
    - tests
  imports:
    - doublemetaphone
  requires:
    - pip
    - pytest
  commands:
    - pip check
    - pytest -v tests

about:
  home: https://github.com/datamade/doublemetaphone
  license: Artistic-2.0
  license_file: LICENSE
  license_family: PSF
  summary: Python wrapper for C++ Double Metaphone
  description: |
    Python wrapper for Stephen Lacy's C++ Implementation of Double
    Metaphone. https://github.com/slacy/double-metaphone
  doc_url: https://github.com/datamade/doublemetaphone
  dev_url: https://github.com/datamade/doublemetaphone

extra:
  recipe-maintainers:
    - proinsias
