appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
travis:
  secure: {BINSTAR_TOKEN: o5s96RTuhHebIFqE5cgYCxXt3Ohe/el1Rb/7si3Z4zsfxBR4tHi5aMbvGleqj7wjufC+ADGUjaYhve6IcqBFt8yqsMTuuRl1M3Bsvn2qUmrrPXlTTfG+f5jT5A5zmn+TiutSquH3f6Rm8cMrNbi5hVRUveKzkn/2Ahd5OnMhYtQZRET+LL8e/00yW4hTIGNHUtBCaUQ/pMCBDC42uMKyznhJhY3yj6WhhYqRCHKGQkZwwbPpGbF7EXmhgWpyZ6VnCFvOINLxj7PPVRIiXhJvfqEOPiHtPC7TEWfC5LHRu5lLRbDNrsrJ4g01o07xtW/srx8eDpLb0petf0mkFrHYVcxF8RiPCuRvN/a/5eeJI4MvTK9PEwku85rNPgCm9aAun+VqS7o218T6BCU2pot+icxKPKRRLs1dNSU6SSjR+w+uvRTwIneWwSas0RFLYmhpHLAJIXbSIfYZoNtcksht+j/3jIDqCJjkWhGNTwxTah9O4iDHHO25IccCGzuzPMnndWSBRyw84pzk9FuIS9RyiRZLfWwEO+pbOCvyu16qcuTsZ1ztKeLMvppOO9grCpEXroujb++AX+HvPm8uB13JrGh8V+TjfMTb45xDmdI/F+FUMsI/3NySei8fbiz9V9de3nXCTf7oEjHGuBIuxV3+ZihJe15Kita9pYXm0bHH9CU=}
conda_forge_output_validation: true
bot:
  automerge: true
