travis:
  secure:
    BINSTAR_TOKEN: dY0aIOq4GpV0xHAd6dVyu/iILzb62D5ukq9iRq5WqoOlHC01pEJijIzxm37MRatCZJNNq3D/mZQsoAyzWEGRkX8bP4TeX3RDcnZHgY0ZZwIOpgPegIZ3ShsLlfbtbX8u+J/Zynp/MbbekMrJejhOceV4NeS5OUf9YPUw6dLdoQxCTRgI0H91bACaMTTTiCp6C1YYuhlr1AP8lpX8KHqmZXjDlhBsuUkA3XNJ/Bien3IJ9rys6hNUwN6hAEiGePdEi9/1kuOgt/EwJDJHt4F1lKJw6m2CGqMF9hf3fCkAfJARFIu9r14UDzau9X1hLTm68YrBLdkq0AQOIFVlKCNGAtFnfy604S/hD91A5omdinkUyvryT2CqqPT0g3dSnU5837a5WzHEBau2khdb5UMR1jKNBSeCANxUGdrFrPOXYR7FGA2fnaMZ5wzOQR8isyruSmgDGzivlSNhwdgMHn6NQA02rS3Serx28N98fA/1HOidZu3DsM2T77nzjtHZoNqSeTyDW9LLOsMX0EpFoNaISecgdvBTcYe48t8Ez9GCsScTd5/ZqIlaRCvkUNqdz6s4oKCbHbpSOckdNEhSHtgZCDep+ZO1vuOcd7er1MBrBUjMEkQbOiX3izICCtDap+kZXDMj+G2GeqGlp60CY86b8JKSMSyNy4wilb02dkYpzk8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
