travis:
  secure:
    BINSTAR_TOKEN: vkJQtEQs+hhVKOlxOWNk73+g79ok5jTycIMo9vpouecZ0fuyq6mT9lKP6q9GeX61J/tOEzP3tNmD3QmO9S987VGAJyZSR4/w+z8JWsKicrKa2hU1UN4Tuk8bv9oG6VSNqRZIc6cP0Ia5ZoRwDn3vmhWzt/vyqfr21e5KY1pxcHyvx1ZaA4jciMVfMxJdoMamkPC8dGKnaJQKgFIoG0xfjrkO8nTr9fvSyCNQDYLFJztoLtdnrdmDnfv+GZvTnwqgaGd1j+ADua6QGyrBYoL/nQSTPy2FNYIpUiAUmE6fsTy5p38bjHpLJeSUJKIgh77AxV46+xahIlmth0GAzHMsLvwsWUD7CdnNW80Kl3QyPynqz2S+ejhk9oIYkIYU8iUppxAsjfi8c/cF+i6mAsDr8BYxSPpN5thlWRzVwvSxkVoaxB/nXX7Ueeja2A5AnjVIBfUG2DLTxrdDaAybu89+qktrDbMdB31I72KwqSRmPl8JpclITmhtk24027eK/pTp8iw9qHjWk+YetUOlb4iqkLQiEPOB6A3lS3pszkT8ML+KOzUNrVj592bwLK8YxlGVYBmPo8p2Abax3idWW+kBnSl3R0nmppQ+zPw8yfUqInXIcz0mRE9vJV9ksjo1LX7KGE+u+VJU3aiVCHkkrVgGDk0BBOgZ7e6TXyAeKJ7u5mo=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
